services:
  db:
    image: postgres
    restart: always
    environment:
  #TODO senha porta host para o env
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cadastro_produto
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cadastro_produto_backend
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: root
      DB_DATABASE: cadastro_produto
      NODE_ENV: development
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cadastro_produto_frontend
    ports:
      - '4200:4200'
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    stdin_open: true
    tty: true

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge