version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cadastro_produto
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'

  app:
    build: .
    container_name: cadastro_produto
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: root
      DB_DATABASE: cadastro_produto
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  postgres_data: